from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
CAT=ROOT/'catalog'
p=CAT/'documents.json'
docs=json.loads(p.read_text(encoding='utf-8'))
new=[
{'file':'Cygames_Lyra_LLM_Code_Review_Operations.md','path':'sources/markdown/Cygames_Lyra_LLM_Code_Review_Operations.md','title':'コードレビュー支援ツール「Lyra」から学ぶ LLM業務システムの運用設計','original':'コードレビュー支援ツール開発から学ぶ.pdf','sourceFormat':'PDF','level':'production / AI system operations','engine':'GitHub / LLM / CloudWatch','tags':['LLM','CodeReview','StructuredOutput','MultiAgent','GitHub','CloudWatch','AIQuality'],'imageCount':3,'images':['sources/markdown/images/lyra__structured_output_ja.svg','sources/markdown/images/lyra__multi_agent_ja.svg','sources/markdown/images/lyra__operations_dashboard_ja.svg']},
{'file':'Cygames_AI_Scenario_Writer_Support_Dify.md','path':'sources/markdown/Cygames_AI_Scenario_Writer_Support_Dify.md','title':'ゲームシナリオライターを支援するAIツール開発の実践 — Dify・Prompt・Human-in-the-Loop','original':'ゲームシナリオライターを支援するAIツール開発の実践 ― 設計とプロンプトの工夫 ―.pdf','sourceFormat':'PDF','level':'production / AI tooling','engine':'Dify / Cygames internal tools','tags':['LLM','Dify','ScenarioWriting','PromptEngineering','StructuredOutput','HumanInTheLoop'],'imageCount':3,'images':['sources/markdown/images/scenario_ai__character_consistency_ja.svg','sources/markdown/images/scenario_ai__tool_suite_ja.svg','sources/markdown/images/scenario_ai__dify_constraints_ja.svg']},
{'file':'Cygames_Shadowverse_Worlds_Beyond_Architecture_Redesign.md','path':'sources/markdown/Cygames_Shadowverse_Worlds_Beyond_Architecture_Redesign.md','title':'Cygames流 最新スマートフォンゲームの技術設計 — Shadowverse: Worlds Beyond アーキテクチャ再設計','original':'Cygames流 最新スマートフォンゲームの技術設計 〜Shadowverse Worlds Beyondにおけるアーキテクチャ再設計の挑戦～.pdf','sourceFormat':'PDF','level':'architecture / production','engine':'Unity / MagicOnion / Shadowverse: Worlds Beyond','tags':['Unity','MagicOnion','ServerAuthoritative','Architecture','Automation','Mobile','ShadowverseWorldsBeyond'],'imageCount':3,'images':['sources/markdown/images/svwb_arch__park_magic_onion_ja.svg','sources/markdown/images/svwb_arch__battle_streaming_ja.svg','sources/markdown/images/svwb_arch__server_battle_logic_ja.svg']},
{'file':'UmaMusume_Video_Production_Quality_Tool.md','path':'sources/markdown/UmaMusume_Video_Production_Quality_Tool.md','title':'ウマ娘 プリティーダービーにおける映像制作のさらなる高品質化 — 素材出力と撮影安定化','original':'ウマ娘 プリティーダービーにおける映像制作のさらなる高品質化へ.pdf','sourceFormat':'PDF','level':'production / tooling','engine':'Unity / Unity Recorder / After Effects','tags':['Unity','VideoProduction','UnityRecorder','AfterEffects','Compositing','EditorTool'],'imageCount':3,'images':['sources/markdown/images/umamusume_video__workflow_ja.svg','sources/markdown/images/umamusume_video__material_outputs_ja.svg','sources/markdown/images/umamusume_video__stable_capture_ja.svg']},
{'file':'Cygames_Neural_Shading_Introduction.md','path':'sources/markdown/Cygames_Neural_Shading_Introduction.md','title':'グラフィックスエンジニアのためのニューラルシェーディング入門','original':'グラフィックスエンジニアのためのニューラルシェーディング入門.pdf','sourceFormat':'PDF','level':'foundation / implementation','engine':'GPU Shader / Slang / SlangPy / Cooperative Vector','tags':['NeuralShading','Slang','SlangPy','CooperativeVector','MLP','NeuralTexture','NeuralGI'],'imageCount':3,'images':['sources/markdown/images/neural_shading__overview_ja.svg','sources/markdown/images/neural_shading__training_ja.svg','sources/markdown/images/neural_shading__slang_coopvec_ja.svg']},
{'file':'Shadowverse_Worlds_Beyond_VFX_3D_Background_Visual_Design.md','path':'sources/markdown/Shadowverse_Worlds_Beyond_VFX_3D_Background_Visual_Design.md','title':'派手さと見やすさは両立できる — Shadowverse: Worlds Beyond エフェクト・3D背景のVisual設計','original':'派手さと見やすさは両立できるエフェクト_3D背景の超進化したビジュアル設計.pdf','sourceFormat':'PDF','level':'visual design / production','engine':'Shadowverse: Worlds Beyond','tags':['ShadowverseWorldsBeyond','VFX','3DBackground','Readability','Shader','PostEffect','VisualDesign'],'imageCount':3,'images':['sources/markdown/images/svwb_visual__design_balance_ja.svg','sources/markdown/images/svwb_visual__effects_ja.svg','sources/markdown/images/svwb_visual__background_readability_ja.svg']},
{'file':'Relink_Endless_Ragnarok_CI_Operations.md','path':'sources/markdown/Relink_Endless_Ragnarok_CI_Operations.md','title':'Relinkを拡張せよ — Endless Ragnarokの開発速度と品質を守るCI運用','original':'Relinkを拡張せよ _GRANBLUE FANTASY Relink_Endless Ragnarokの開発速度と品質を守るCI運用.pdf','sourceFormat':'PDF','level':'production / CI quality','engine':'Jenkins / Datadog / Cygames console pipeline','tags':['CI','CD','Datadog','Jenkins','StaticAnalysis','SnapshotQA','VisualRegression'],'imageCount':3,'images':['sources/markdown/images/relink_ci__three_pillars_ja.svg','sources/markdown/images/relink_ci__datadog_ja.svg','sources/markdown/images/relink_ci__snapshotqa_ja.svg']},
{'file':'Relink_Endless_Ragnarok_Battle_Production.md','path':'sources/markdown/Relink_Endless_Ragnarok_Battle_Production.md','title':'GRANBLUE FANTASY: Relink - Endless Ragnarok のBattle制作事例 — 最高のCharacter Gameを目指して','original':'GRANBLUE FANTASY Relink_Endless Ragnarokのバトル制作事例.pdf','sourceFormat':'PDF','level':'game design / production','engine':'GRANBLUE FANTASY: Relink - Endless Ragnarok','tags':['CombatDesign','CompanionAI','BehaviorTree','FSM','AssistMode','Iteration','Relink'],'imageCount':3,'images':['sources/markdown/images/relink_battle__84_variants_ja.svg','sources/markdown/images/relink_battle__companion_ai_ja.svg','sources/markdown/images/relink_battle__assist_mode_ja.svg']},
{'file':'Relink_Endless_Ragnarok_VFX_Design.md','path':'sources/markdown/Relink_Endless_Ragnarok_VFX_Design.md','title':'アートとゲームデザインをつなぐVFX設計 — Endless Ragnarokにおける表現と可読性','original':'アートとゲームデザインを繋ぐVFX設計.pdf','sourceFormat':'PDF','level':'visual design / game design','engine':'GRANBLUE FANTASY: Relink - Endless Ragnarok','tags':['VFX','Readability','CombatDesign','InformationDensity','ArtDirection','Relink'],'imageCount':3,'images':['sources/markdown/images/relink_vfx__support_information_ja.svg','sources/markdown/images/relink_vfx__three_axis_density_ja.svg','sources/markdown/images/relink_vfx__art_readability_ja.svg']}]
known={d['file'] for d in docs}
docs.extend(x for x in new if x['file'] not in known)
p.write_text(json.dumps(docs,ensure_ascii=False,separators=(',',':'))+'\n',encoding='utf-8')

index=(ROOT/'index.html').read_text(encoding='utf-8')
index=index.replace('<div class="value">81</div><div class="label">登録Source</div>','<div class="value">90</div><div class="label">登録Source</div>')
index=index.replace('<div class="value">19</div><div class="label">強化Markdown</div>','<div class="value">28</div><div class="label">強化Markdown</div>')
index=index.replace('<div class="value">60</div><div class="label">重要図版</div>','<div class="value">87</div><div class="label">重要図版</div>')
index=index.replace('<div class="value">19</div><div class="label">原資料 PDF/PPTX</div>','<div class="value">28</div><div class="label">原資料 PDF/PPTX</div>')
index=index.replace('<div class="kicker">19 Documents</div>','<div class="kicker">28 Documents</div>')
(ROOT/'index.html').write_text(index,encoding='utf-8')
print(f'Portal synchronized: {len(docs)} documents')
