const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname,'..');
const context = {URL,URLSearchParams,window:{addEventListener(){}},location:{pathname:'/repositories.html'}};
vm.runInNewContext(fs.readFileSync(path.join(root,'assets/catalog.js'),'utf8'),context);
assert.equal(context.window.MRCCatalog.resourceHref({id:'RES-X',kind:'repository',url:'https://github.com/a/b'}),'repository.html?id=RES-X');
vm.runInNewContext(fs.readFileSync(path.join(root,'assets/repositories.js'),'utf8'),context);
const R=context.window.MRCRepositories,C=context.window.MRCCatalog;
const row={id:'RES-X',kind:'repository',title:'Shading Demo <script>',canonicalUrl:'https://github.com/Unity-Technologies/shading-rate-demo',tags:['Unity','URP'],topics:['Variable Rate Shading'],summary:'Reference implementation'};
assert.equal(R.repositoryIdentity(row.canonicalUrl).path,'Unity-Technologies / shading-rate-demo');
for(const bad of ['https://user:pass@github.com/a/b','javascript:alert(1)','https://gitlab.com/a/b','https://github.com/a/b/tree/main','https://github.com/a/b?token=x','https://github.com/a/%62','https://github.com/a/..','https://github.com/a/b#readme','https://github.com/a/%2e/b','https://github.com/a/x/%2e%2e/b','https://github.com/a/b?','https://github.com/a/b#','https://github.com:443/a/b','https://github.com/a/b\\x']) assert.equal(R.repositoryIdentity(bad),null,bad);
for(const q of ['shading','Unity-Technologies/shading-rate-demo','Variable Rate','Reference','URP']) assert.equal(R.filterRepositories([row],{q}).length,1,q);
assert.equal(R.filterRepositories([row,{...row,kind:'website'}],{tag:'Unity'}).length,1);
assert.equal(R.filterRepositories([row],{tag:'UnrealEngine'}).length,0);
assert.equal(R.filterRepositories([row],{q:'missing'}).length,0);
const card=R.renderCard(row,C);
assert.match(card,/target="_blank" rel="noopener noreferrer"/);
assert.match(card,/repository.html\?id=RES-X/);
assert.match(card,/Shading Demo &lt;script&gt;/);
assert.doesNotMatch(card,/<img|<script>/);
assert.match(card,/repository-topics/);
const resources=[row,{id:'RES-Y',kind:'document',title:'Related doc'},{id:'RES-Z',kind:'website',title:'Other'}];
const collections=[{id:'COL-X',title:'Rendering',resources:[{id:'RES-X',role:'implementation'}]}];
const relations=[{from:'RES-X',to:'RES-Y',relation:'implements'}];
const detail=R.renderDetail(row,{resources,collections,relations},C);
assert.match(detail,/collection.html\?id=COL-X/);
assert.match(detail,/document.html\?id=RES-Y/);
assert.doesNotMatch(detail,/Other|RES-Z/);
const html=fs.readFileSync(path.join(root,'repositories.html'),'utf8');
for(const id of ['q','tag','clear','list','count','result-meta','pagination']) assert.equal((html.match(new RegExp(`id="${id}"`,'g')) || []).length,1,`unique ${id}`);
console.log('OK: repository URL, filters, cards, detail and canonical graph routing');
