from __future__ import annotations

from argparse import ArgumentParser
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo
import json
import sys

from validate_trends import CATEGORIES, MAX_ITEMS_PER_DAY, MAX_SUMMARY_LENGTH, TYPES, validate, validate_url

ROOT = Path(__file__).resolve().parents[1]
TREND_PATH = ROOT / 'data' / 'trends.json'
TOKYO = ZoneInfo('Asia/Tokyo')


def load_items(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding='utf-8'))
    items = data.get('items') if isinstance(data, dict) else data
    if not isinstance(items, list):
        raise ValueError('input must be an array or {"items": [...]}')
    return items


def normalize_item(item: dict) -> dict:
    if not isinstance(item, dict):
        raise ValueError('every trend item must be an object')

    title = str(item.get('title', '')).strip()
    url = str(item.get('url', '')).strip()
    source = str(item.get('source', '')).strip()
    category = str(item.get('category', '')).strip()
    trend_type = str(item.get('type', '')).strip().upper()
    summary = str(item.get('summary', '')).strip()
    published_at = item.get('publishedAt')
    tags = item.get('tags', [])
    score = item.get('score')

    if not title:
        raise ValueError('title is required')
    if not validate_url(url):
        raise ValueError(f'invalid URL: {url}')
    if not source:
        raise ValueError(f'source is required: {url}')
    if category not in CATEGORIES:
        raise ValueError(f'invalid category {category}: {url}')
    if trend_type not in TYPES:
        raise ValueError(f'invalid type {trend_type}: {url}')
    if not summary or len(summary) > MAX_SUMMARY_LENGTH:
        raise ValueError(f'summary must be 1..{MAX_SUMMARY_LENGTH} chars: {url}')
    if not isinstance(score, int) or isinstance(score, bool) or not 0 <= score <= 100:
        raise ValueError(f'score must be integer 0..100: {url}')
    if not isinstance(tags, list):
        raise ValueError(f'tags must be an array: {url}')

    clean_tags = []
    for tag in tags:
        text = str(tag).strip()
        if text and text not in clean_tags:
            clean_tags.append(text)
        if len(clean_tags) >= 8:
            break

    return {
        'title': title,
        'url': url,
        'source': source,
        'publishedAt': published_at,
        'category': category,
        'type': trend_type,
        'summary': summary,
        'tags': clean_tags,
        'score': score,
    }


def main() -> int:
    parser = ArgumentParser(description='Safely replace one day of Trend Radar data and retain only three days.')
    parser.add_argument('--input', required=True, help='JSON array or {"items": [...]} generated by the research task')
    parser.add_argument('--date', help='Target YYYY-MM-DD. Defaults to today in Asia/Tokyo.')
    args = parser.parse_args()

    now = datetime.now(TOKYO)
    target_date = args.date or now.date().isoformat()

    try:
        incoming = [normalize_item(item) for item in load_items(Path(args.input))]
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f'FAILED: {exc}')
        return 1

    # Same URL is one Trend. Higher score wins within the incoming batch.
    deduped: dict[str, dict] = {}
    for item in incoming:
        previous = deduped.get(item['url'])
        if previous is None or item['score'] > previous['score']:
            deduped[item['url']] = item

    items = sorted(deduped.values(), key=lambda item: (-item['score'], item['title']))[:MAX_ITEMS_PER_DAY]
    for index, item in enumerate(items, start=1):
        item['id'] = f'TREND-{target_date.replace("-", "")}-{index:03d}'

    try:
        existing = json.loads(TREND_PATH.read_text(encoding='utf-8'))
    except (OSError, json.JSONDecodeError):
        existing = {'schemaVersion': '1.0', 'generatedAt': None, 'days': []}

    new_urls = {item['url'] for item in items}
    days = []
    for day in existing.get('days', []):
        if not isinstance(day, dict) or day.get('date') == target_date:
            continue
        old_items = [item for item in day.get('items', []) if item.get('url') not in new_urls]
        days.append({'date': day.get('date'), 'items': old_items})

    days.append({'date': target_date, 'items': items})
    days = sorted(days, key=lambda day: str(day.get('date', '')), reverse=True)[:3]

    output = {
        'schemaVersion': '1.0',
        'generatedAt': now.isoformat(timespec='seconds'),
        'days': days,
    }

    errors = validate(output)
    if errors:
        print('FAILED: generated Trend Radar dataset is invalid')
        for error in errors:
            print('-', error)
        return 1

    TREND_PATH.write_text(json.dumps(output, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'OK: wrote {len(items)} items for {target_date}; retained {len(days)} day(s)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
